travis:
  secure:
    BINSTAR_TOKEN: ReNT/WHNVHNwY3ys8n/oS88nis7KS4x1ZseL/mkWk1QLRHwsZknFQm8kdYRJqgHnjgvZQLxNzgBG0g/EfE18U8coc3I+oPNBKXJf7LfgLpUs0Zodlyrgx3UrdkkkuzhPMAQnWj2lUwMjPPPr3E5rvCerCdfyV6xrfYib6YfezgWkwa8kyf/DnF+Yfp3dL0zpIDSEVsXRpT4JU2MzpL/Pr6Ir0lqCgEa8PqKxa0iV5r9ZkYBWxgaZOx5YGB7l81JX5SYZY5bwZeEabBB0Xg5mraozKDbEFD4z0JMSJ7E/Ue1EHeXlJKBkjxuEmwqovtO2qxhb9rDlG5DBl24wBahg26P/XTZRnloxaVz2nuiHt/X4qlbyWQ692oOd4iGeD4UZMf5kK5UN+MPPUczLImKrp1Ps26shWCPj8jPLUimEsWsh2DDgtMSvv38LmdPjnPgD7CvDH4aZ1nyaR8qBEIZd+Cix898qtXbVrg3obvTEJMu7E74CeMB2+c1M9jCM6JgSzxIm9XHxnMHzKUXEpVFAPlzwnBGqnzWrJXA4KiLkuN8bbn2xivfVRoyatrYGCK8IIJmAZOTV0V1IjKUKyQ36ZVXkA4NiG/KW7hR3xdUgz+9GpXmvqVJe7T1m6yeptoOFYEb0emZ72AIJjj0WbTpONLWKoD0+cD85Wk3y27LGCAU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
