travis:
  secure:
    BINSTAR_TOKEN: Tb/ygoTHQDO9VM5wJNVLiQakSfbkHZyvnnQEKQ7YozG8jAPsTpIghk7ttxlU9zsOU5MhtTbNBslatnmpK+Xz1Q7jiyLUwwtlK3qQwGyrky1ueJDX/kwPLMWd1b24HX2VOtT71uBmBepalwgQMKPXTeM/2CGvsXTSn9SnWuXGDNWITLhvSdIXo61Sqtw6eeaD+8TL4jkd6KK7/Y3KBvh2AqoXxfMxoK9Pwr4Cnj1I4DlO5Yl420mh1f6KsBH61VvOTtGJV7NxFRXswgLGH91x3ZomWiLqVIqi1/OlUYMFwocecaaxQ6AbqtGCVErJTZv/awupSx7GJyCqxwftbwTCJC1qC6SBA4uGovfqpmnSbLZAm8+eke5oiyKsJq2MaS8BlnDK0G6tfYbwdMR+/ey8f6omLDOuKTYdeemm62ssiWRMfYI2Of6MCqerIDRtcftT4OsU5PHtOo8wK57omRSI/NJxBbnpCQxnjdFx/S75Yl2e6SCiIDlD3/Wy2HUsgtWn0/pra0SJGGHCKMbc+qyKP835V2AdkNkMn8gD6+7oNiGuy0XxmnZ/oIeCDP3DAxEfDv/kfCEHYeRGNH8V+Eso835gb9OcVcwvZbwYwqmNCKqoz5o9+QuE+qtjGWh6xmJ/l4xpwHF7Robu/i5L04ZW7O0yB/bG3dM411BlxU8ScNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
